import json

offices_and_pois = [
    # --- City Mart & Marketplace Branches (Every Branch in Yangon) ---
    {
        "id": "cm-01",
        "name": "City Mart Supermarket (Myaynigone)",
        "name_mm": "စတီးမတ် မြေနီကုန်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Sanchaung",
        "township_mm": "စမ်းချောင်း",
        "road": "Shin Saw Pu Road / Pyay Road",
        "road_mm": "ရှင်စောပုလမ်း / ပြည်လမ်း",
        "lat": 16.804820,
        "lng": 96.136540,
        "tags": ["city mart", "supermarket", "myaynigone", "sanchaung", "စတီးမတ်", "မြေနီကုန်း", "စမ်းချောင်း"]
    },
    {
        "id": "cm-02",
        "name": "City Mart Supermarket (Junction Square)",
        "name_mm": "စတီးမတ် ဂျန်းရှင်းစကွဲ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Kamayut",
        "township_mm": "ကမာရွတ်",
        "road": "Pyay Road & Kyun Taw Road",
        "road_mm": "ပြည်လမ်း နှင့် ကျွန်းတောလမ်း",
        "lat": 16.818950,
        "lng": 96.130230,
        "tags": ["city mart", "junction square", "kamayut", "supermarket", "စတီးမတ်", "ဂျန်းရှင်းစကွဲ", "ကမာရွတ်"]
    },
    {
        "id": "cm-03",
        "name": "City Mart Supermarket (Sule Square)",
        "name_mm": "စတီးမတ် ဆူးလေစကွဲ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Kyauktada",
        "township_mm": "ကျောက်တံတား",
        "road": "Sule Pagoda Road",
        "road_mm": "ဆူးလေဘုရားလမ်း",
        "lat": 16.776650,
        "lng": 96.158520,
        "tags": ["city mart", "sule square", "kyauktada", "downtown", "စတီးမတ်", "ဆူးလေစကွဲ", "ကျောက်တံတား"]
    },
    {
        "id": "cm-04",
        "name": "City Mart Supermarket (Hledan Center)",
        "name_mm": "စတီးမတ် လှည်းတန်းစင်တာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Kamayut",
        "township_mm": "ကမာရွတ်",
        "road": "Hledan Road & Pyay Road",
        "road_mm": "လှည်းတန်းလမ်း နှင့် ပြည်လမ်း",
        "lat": 16.825840,
        "lng": 96.128710,
        "tags": ["city mart", "hledan", "hledan center", "kamayut", "စတီးမတ်", "လှည်းတန်းစင်တာ", "ကမာရွတ်"]
    },
    {
        "id": "cm-05",
        "name": "City Mart Supermarket (47th Street)",
        "name_mm": "စတီးမတ် ၄၇ လမ်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Botahtaung",
        "township_mm": "ဗိုလ်တထောင်",
        "road": "Anawrahta Road & 47th Street",
        "road_mm": "အနော်ရထာလမ်း နှင့် ၄၇ လမ်း",
        "lat": 16.777210,
        "lng": 96.170320,
        "tags": ["city mart", "47th st", "botahtaung", "anawrahta", "စတီးမတ်", "၄၇လမ်း", "ဗိုလ်တထောင်"]
    },
    {
        "id": "cm-06",
        "name": "City Mart Supermarket (Chinatown 19th St)",
        "name_mm": "စတီးမတ် တရုတ်တန်း ၁၉ လမ်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Latha",
        "township_mm": "လသာ",
        "road": "Mahabandoola Road & 19th Street",
        "road_mm": "မဟာဗန္ဓုလလမ်း နှင့် ၁၉ လမ်း",
        "lat": 16.776050,
        "lng": 96.150740,
        "tags": ["city mart", "chinatown", "19th street", "latha", "စတီးမတ်", "တရုတ်တန်း", "လသာ"]
    },
    {
        "id": "cm-07",
        "name": "City Mart Supermarket (Aung San Stadium)",
        "name_mm": "စတီးမတ် အောင်ဆန်းအားကစားကွင်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Mingalar Taung Nyunt",
        "township_mm": "မင်္ဂလာတောင်ညွန့်",
        "road": "Upper Pansodan Road",
        "road_mm": "အထက်ပန်းဆိုးတန်းလမ်း",
        "lat": 16.782500,
        "lng": 96.162050,
        "tags": ["city mart", "aung san stadium", "mingalar taung nyunt", "pansodan", "စတီးမတ်", "အောင်ဆန်းကွင်း"]
    },
    {
        "id": "cm-08",
        "name": "City Mart Supermarket (Parami)",
        "name_mm": "စတီးမတ် ပါရမီ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Parami Road & Chindwin Street",
        "road_mm": "ပါရမီလမ်း နှင့် ချင်းတွင်းလမ်း",
        "lat": 16.848520,
        "lng": 96.143210,
        "tags": ["city mart", "parami", "mayangone", "စတီးမတ်", "ပါရမီ", "မရမ်းကုန်း"]
    },
    {
        "id": "cm-09",
        "name": "City Mart Supermarket (Waizayantar)",
        "name_mm": "စတီးမတ် ဝေဇယန္တာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Thingangyun",
        "township_mm": "သင်္ဃန်းကျွန်း",
        "road": "Waizayantar Road",
        "road_mm": "ဝေဇယန္တာလမ်း",
        "lat": 16.832250,
        "lng": 96.185620,
        "tags": ["city mart", "waizayantar", "thingangyun", "စတီးမတ်", "ဝေဇယန္တာ", "သင်္ဃန်းကျွန်း"]
    },
    {
        "id": "cm-10",
        "name": "City Mart Supermarket (Thamine Junction)",
        "name_mm": "စတီးမတ် သမိုင်းလမ်းဆုံ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Hlaing",
        "township_mm": "လှိုင်",
        "road": "Yangon-Insein Road & Thamine Junction",
        "road_mm": "ရန်ကုန်-အင်းစိန်လမ်း သမိုင်းလမ်းဆုံ",
        "lat": 16.853040,
        "lng": 96.120510,
        "tags": ["city mart", "thamine", "hlaing", "junction", "စတီးမတ်", "သမိုင်းလမ်းဆုံ", "လှိုင်"]
    },
    {
        "id": "cm-11",
        "name": "City Mart Supermarket (Yuzana Plaza)",
        "name_mm": "စတီးမတ် ယုဇနပလာဇာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Mingalar Taung Nyunt",
        "township_mm": "မင်္ဂလာတောင်ညွန့်",
        "road": "Banyadala Road",
        "road_mm": "ဗညားဒလလမ်း",
        "lat": 16.793210,
        "lng": 96.169540,
        "tags": ["city mart", "yuzana plaza", "banyadala", "mingalar taung nyunt", "စတီးမတ်", "ယုဇနပလာဇာ"]
    },
    {
        "id": "cm-12",
        "name": "City Mart Supermarket (North Dagon Pinlon)",
        "name_mm": "စတီးမတ် ပင်လုံ မြောက်ဒဂုံ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "North Dagon",
        "township_mm": "မြောက်ဒဂုံ",
        "road": "Pinlon Road",
        "road_mm": "ပင်လုံလမ်း",
        "lat": 16.872030,
        "lng": 96.208540,
        "tags": ["city mart", "pinlon", "north dagon", "မြောက်ဒဂုံ", "ပင်လုံ", "စတီးမတ်"]
    },
    {
        "id": "cm-13",
        "name": "City Mart Supermarket (South Okkalapa)",
        "name_mm": "စတီးမတ် တောင်ဥက္ကလာပ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "South Okkalapa",
        "township_mm": "တောင်ဥက္ကလာပ",
        "road": "Thanthumar Road",
        "road_mm": "သံသုမာလမ်း",
        "lat": 16.838520,
        "lng": 96.175030,
        "tags": ["city mart", "south okkalapa", "thanthumar", "စတီးမတ်", "တောင်ဥက္ကလာပ"]
    },
    {
        "id": "cm-14",
        "name": "City Mart Supermarket (Insein)",
        "name_mm": "စတီးမတ် အင်းစိန်",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Insein",
        "township_mm": "အင်းစိန်",
        "road": "Yangon-Insein Road & Min Gyi Road",
        "road_mm": "ရန်ကုန်-အင်းစိန်လမ်း နှင့် မင်းကြီးလမ်း",
        "lat": 16.885020,
        "lng": 96.108040,
        "tags": ["city mart", "insein", "min gyi", "စတီးမတ်", "အင်းစိန်"]
    },
    {
        "id": "cm-15",
        "name": "City Mart Supermarket (Star City Thanlyin)",
        "name_mm": "စတီးမတ် စတားစီးတီး သန်လျင်",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Thanlyin",
        "township_mm": "သန်လျင်",
        "road": "Star City Complex Road",
        "road_mm": "စတားစီးတီးလမ်း",
        "lat": 16.755010,
        "lng": 96.242050,
        "tags": ["city mart", "star city", "thanlyin", "စတီးမတ်", "စတားစီးတီး", "သန်လျင်"]
    },
    {
        "id": "cm-16",
        "name": "City Mart Supermarket (Shwe Pyi Thar)",
        "name_mm": "စတီးမတ် ရွှေပြည်သာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Shwepyitha",
        "township_mm": "ရွှေပြည်သာ",
        "road": "No. 4 Main Road",
        "road_mm": "အမှတ်(၄)လမ်းမကြီး",
        "lat": 16.962040,
        "lng": 96.115020,
        "tags": ["city mart", "shwepyitha", "no 4 road", "စတီးမတ်", "ရွှေပြည်သာ"]
    },
    {
        "id": "cm-17",
        "name": "City Mart Supermarket (Hlaingtharyar)",
        "name_mm": "စတီးမတ် လှိုင်သာယာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Anawrahta Road, FMI City Gate",
        "road_mm": "အနော်ရထာလမ်း FMI အိမ်ရာ",
        "lat": 16.862030,
        "lng": 96.068040,
        "tags": ["city mart", "hlaingtharyar", "fmi", "စတီးမတ်", "လှိုင်သာယာ"]
    },
    {
        "id": "cm-18",
        "name": "City Mart Supermarket (Yankin Center)",
        "name_mm": "စတီးမတ် ရန်ကင်းစင်တာ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Yankin",
        "township_mm": "ရန်ကင်း",
        "road": "Saya San Road",
        "road_mm": "ဆရာစံလမ်း",
        "lat": 16.822050,
        "lng": 96.168030,
        "tags": ["city mart", "yankin", "saya san", "စတီးမတ်", "ရန်ကင်း"]
    },
    {
        "id": "cm-19",
        "name": "City Mart Supermarket (Dawbon)",
        "name_mm": "စတီးမတ် ဒေါပုံ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Dawbon",
        "township_mm": "ဒေါပုံ",
        "road": "Yamonar Road",
        "road_mm": "ယမုံနာလမ်း",
        "lat": 16.782040,
        "lng": 96.189020,
        "tags": ["city mart", "dawbon", "yamonar", "စတီးမတ်", "ဒေါပုံ"]
    },
    {
        "id": "cm-20",
        "name": "City Mart Supermarket (North Okkalapa)",
        "name_mm": "စတီးမတ် မြောက်ဥက္ကလာပ",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "North Okkalapa",
        "township_mm": "မြောက်ဥက္ကလာပ",
        "road": "Thudhamar Road",
        "road_mm": "သုဓမ္မာလမ်း",
        "lat": 16.881020,
        "lng": 96.168040,
        "tags": ["city mart", "north okkalapa", "thudhamar", "စတီးမတ်", "မြောက်ဥက္ကလာပ"]
    },
    {
        "id": "cm-21",
        "name": "Marketplace by City Mart (Golden Valley)",
        "name_mm": "မားကက်ပလေ့စ် ရွှေတောင်ကြား",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Bahan",
        "township_mm": "ဗဟန်း",
        "road": "Dhamazedi Road",
        "road_mm": "ဓမ္မစေတီလမ်း",
        "lat": 16.809050,
        "lng": 96.148520,
        "tags": ["marketplace", "city mart", "golden valley", "dhamazedi", "bahan", "မားကက်ပလေ့စ်", "ရွှေတောင်ကြား", "ဗဟန်း"]
    },
    {
        "id": "cm-22",
        "name": "Marketplace by City Mart (6.5 Miles Pyay Road)",
        "name_mm": "မားကက်ပလေ့စ် ၆ မိုင်ခွဲ ပြည်လမ်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Pyay Road (6.5 Miles)",
        "road_mm": "ပြည်လမ်း (၆ မိုင်ခွဲ)",
        "lat": 16.845030,
        "lng": 96.132040,
        "tags": ["marketplace", "city mart", "6.5 miles", "pyay road", "mayangone", "မားကက်ပလေ့စ်", "ပြည်လမ်း", "မရမ်းကုန်း"]
    },
    {
        "id": "cm-23",
        "name": "Marketplace by City Mart (Central Boulevard)",
        "name_mm": "မားကက်ပလေ့စ် စင်ထရယ် ဘိုလီးဗတ်",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Yankin",
        "township_mm": "ရန်ကင်း",
        "road": "Kabar Aye Pagoda Road",
        "road_mm": "ကမ္ဘာအေးဘုရားလမ်း",
        "lat": 16.831040,
        "lng": 96.156020,
        "tags": ["marketplace", "city mart", "central boulevard", "kabar aye", "yankin", "မားကက်ပလေ့စ်", "ရန်ကင်း"]
    },
    {
        "id": "cm-24",
        "name": "Marketplace by City Mart (City Mall St. John)",
        "name_mm": "မားကက်ပလေ့စ် စိန့်ဂျွန်း",
        "category": "City Mart Branch",
        "category_mm": "စတီးမတ်ဆိုင်ခွဲ",
        "township": "Lanmadaw",
        "township_mm": "လမ်းမတော်",
        "road": "Pyay Road & Min Ye Kyaw Swar Road",
        "road_mm": "ပြည်လမ်း နှင့် မင်းရဲကျော်စွာလမ်း",
        "lat": 16.784520,
        "lng": 96.141530,
        "tags": ["marketplace", "city mart", "city mall", "st john", "lanmadaw", "မားကက်ပလေ့စ်", "စိန့်ဂျွန်း", "လမ်းမတော်"]
    },

    # --- Ocean Supercenters & Major Hypermarkets ---
    {
        "id": "hyp-01",
        "name": "Ocean Supercenter (North Point 9 Miles)",
        "name_mm": "အိုရှန်း ၉ မိုင် စူပါစင်တာ",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Pyay Road (9 Miles)",
        "road_mm": "ပြည်လမ်း (၉ မိုင်)",
        "lat": 16.876520,
        "lng": 96.128030,
        "tags": ["ocean", "supercenter", "north point", "9 miles", "mayangone", "အိုရှန်း", "၉မိုင်"]
    },
    {
        "id": "hyp-02",
        "name": "Ocean Supercenter (Pazundaung)",
        "name_mm": "အိုရှန်း ပုဇွန်တောင်",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Pazundaung",
        "township_mm": "ပုဇွန်တောင်",
        "road": "Upper Pazundaung Road",
        "road_mm": "အထက်ပုဇွန်တောင်လမ်း",
        "lat": 16.792040,
        "lng": 96.177020,
        "tags": ["ocean", "supercenter", "pazundaung", "အိုရှန်း", "ပုဇွန်တောင်"]
    },
    {
        "id": "hyp-03",
        "name": "Ocean Supercenter (Tamwe Junction)",
        "name_mm": "အိုရှန်း တာမွေ",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Tamwe",
        "township_mm": "တာမွေ",
        "road": "Kyaikkasan Road & Banyadala Road",
        "road_mm": "ကျိုက္ကဆံလမ်း နှင့် ဗညားဒလလမ်း",
        "lat": 16.808020,
        "lng": 96.171040,
        "tags": ["ocean", "supercenter", "tamwe", "kyaikkasan", "အိုရှန်း", "တာမွေ"]
    },
    {
        "id": "hyp-04",
        "name": "Ocean Supercenter (Hlaingtharyar)",
        "name_mm": "အိုရှန်း လှိုင်သာယာ",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Yangon-Pathein Highway",
        "road_mm": "ရန်ကုန်-ပုသိမ်လမ်းမကြီး",
        "lat": 16.868030,
        "lng": 96.059040,
        "tags": ["ocean", "supercenter", "hlaingtharyar", "အိုရှန်း", "လှိုင်သာယာ"]
    },
    {
        "id": "hyp-05",
        "name": "Ocean Supercenter (East Dagon)",
        "name_mm": "အိုရှန်း အရှေ့ဒဂုံ",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "East Dagon",
        "township_mm": "အရှေ့ဒဂုံ",
        "road": "Min Ye Kyaw Swar Road",
        "road_mm": "မင်းရဲကျော်စွာလမ်း",
        "lat": 16.863040,
        "lng": 96.241020,
        "tags": ["ocean", "supercenter", "east dagon", "အိုရှန်း", "အရှေ့ဒဂုံ"]
    },
    {
        "id": "hyp-06",
        "name": "Makro Myanmar Supermarket",
        "name_mm": "မက်ခရို စူပါမားကတ်",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Mingalar Taung Nyunt",
        "township_mm": "မင်္ဂလာတောင်ညွန့်",
        "road": "Min Nandar Road & Upper Pazundaung Road",
        "road_mm": "မင်းနန္ဒာလမ်း နှင့် အထက်ပုဇွန်တောင်လမ်း",
        "lat": 16.787030,
        "lng": 96.175040,
        "tags": ["makro", "supermarket", "wholesale", "mingalar taung nyunt", "မက်ခရို"]
    },
    {
        "id": "hyp-07",
        "name": "Capital Hypermarket (Dawbon)",
        "name_mm": "ကက်ပီတယ် ဒေါပုံ",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Dawbon",
        "township_mm": "ဒေါပုံ",
        "road": "Min Nandar Road",
        "road_mm": "မင်းနန္ဒာလမ်း",
        "lat": 16.783020,
        "lng": 96.185030,
        "tags": ["capital", "hypermarket", "dawbon", "min nandar", "ကက်ပီတယ်", "ဒေါပုံ"]
    },
    {
        "id": "hyp-08",
        "name": "Capital Hypermarket (Thamine)",
        "name_mm": "ကက်ပီတယ် သမိုင်း",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Bayint Naung Road",
        "road_mm": "ဘုရင့်နောင်လမ်း",
        "lat": 16.852030,
        "lng": 96.115040,
        "tags": ["capital", "hypermarket", "thamine", "bayint naung", "ကက်ပီတယ်", "သမိုင်း"]
    },
    {
        "id": "hyp-09",
        "name": "Sein Gay Har Super Center (Pyay Road)",
        "name_mm": "စိန်ဂေဟာ စူပါစင်တာ ပြည်လမ်း",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Pyay Road (8 Miles)",
        "road_mm": "ပြည်လမ်း (၈ မိုင်)",
        "lat": 16.841020,
        "lng": 96.133040,
        "tags": ["sein gay har", "pyay road", "mayangone", "စိန်ဂေဟာ", "ပြည်လမ်း"]
    },
    {
        "id": "hyp-10",
        "name": "Gamone Pwint Shopping Mall (Kabar Aye)",
        "name_mm": "ဂမုန်းပွင့် ကမ္ဘာအေး",
        "category": "Supermarket & Mall",
        "category_mm": "စူပါမားကတ်နှင့်ကုန်တိုက်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Kabar Aye Pagoda Road",
        "road_mm": "ကမ္ဘာအေးဘုရားလမ်း",
        "lat": 16.858020,
        "lng": 96.154030,
        "tags": ["gamone pwint", "kabar aye", "mayangone", "ဂမုန်းပွင့်", "ကမ္ဘာအေး"]
    },

    # --- Major Office Towers & Corporate IT Parks ---
    {
        "id": "off-01",
        "name": "Junction City Office Tower",
        "name_mm": "ဂျန်းရှင်းစီးတီး ရုံးတာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Pabedan",
        "township_mm": "ပန်းဘဲတန်း",
        "road": "Bogyoke Aung San Road & Shwedagon Pagoda Road",
        "road_mm": "ဗိုလ်ချုပ်အောင်ဆန်းလမ်း နှင့် ရွှေတိဂုံဘုရားလမ်း",
        "lat": 16.778540,
        "lng": 96.154520,
        "tags": ["junction city", "office tower", "pabedan", "bogyoke road", "ဂျန်းရှင်းစီးတီး", "ပန်းဘဲတန်း"]
    },
    {
        "id": "off-02",
        "name": "Times City Yangon Office Tower",
        "name_mm": "တိုင်းမ်စီးတီး ရုံးတာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Kamayut",
        "township_mm": "ကမာရွတ်",
        "road": "Han Thar Waddy Road & Kyun Taw Road",
        "road_mm": "ဟံသာဝတီလမ်း နှင့် ကျွန်းတောလမ်း",
        "lat": 16.815520,
        "lng": 96.128540,
        "tags": ["times city", "office tower", "kamayut", "hantharwaddy", "တိုင်းမ်စီးတီး", "ကမာရွတ်"]
    },
    {
        "id": "off-03",
        "name": "Myanmar Plaza & HAGL Office Towers",
        "name_mm": "မြန်မာပလာဇာ နှင့် HAGL တာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Bahan",
        "township_mm": "ဗဟန်း",
        "road": "Kabar Aye Pagoda Road",
        "road_mm": "ကမ္ဘာအေးဘုရားလမ်း",
        "lat": 16.819540,
        "lng": 96.155520,
        "tags": ["myanmar plaza", "hagl", "office tower", "bahan", "kabar aye", "မြန်မာပလာဇာ", "ဗဟန်း"]
    },
    {
        "id": "off-04",
        "name": "Sule Square Commercial Office Tower",
        "name_mm": "ဆူးလေစကွဲ စီးပွားရေးရုံးတာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Kyauktada",
        "township_mm": "ကျောက်တံတား",
        "road": "Sule Pagoda Road",
        "road_mm": "ဆူးလေဘုရားလမ်း",
        "lat": 16.776650,
        "lng": 96.158520,
        "tags": ["sule square", "office tower", "kyauktada", "downtown", "ဆူးလေစကွဲ", "ကျောက်တံတား"]
    },
    {
        "id": "off-05",
        "name": "MICT Park (Myanmar IT Park)",
        "name_mm": "အမ်အိုင်စီတီ ပါ့ခ် နည်းပညာဥယျာဉ်",
        "category": "IT & Business Park",
        "category_mm": "နည်းပညာနှင့်စီးပွားရေးဇုန်",
        "township": "Hlaing",
        "township_mm": "လှိုင်",
        "road": "Hlaing Universities Campus Road",
        "road_mm": "လှိုင်တက္ကသိုလ်နယ်မြေလမ်း",
        "lat": 16.852520,
        "lng": 96.130540,
        "tags": ["mict park", "it park", "hlaing", "software", "tech", "အမ်အိုင်စီတီ", "လှိုင်"]
    },
    {
        "id": "off-06",
        "name": "Kantharyar Centre Office Tower",
        "name_mm": "ကန်သာယာစင်တာ ရုံးတာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Mingalar Taung Nyunt",
        "township_mm": "မင်္ဂလာတောင်ညွန့်",
        "road": "Kan Yeik Tha Road & U Aung Myat Road",
        "road_mm": "ကန်ရိပ်သာလမ်း နှင့် ဦးအောင်မြတ်လမ်း",
        "lat": 16.791520,
        "lng": 96.162540,
        "tags": ["kantharyar centre", "office tower", "mingalar taung nyunt", "ကန်သာယာစင်တာ"]
    },
    {
        "id": "off-07",
        "name": "Sakura Tower",
        "name_mm": "ဆာကူရာတာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Kyauktada",
        "township_mm": "ကျောက်တံတား",
        "road": "Bogyoke Aung San Road & Sule Pagoda Road",
        "road_mm": "ဗိုလ်ချုပ်အောင်ဆန်းလမ်း နှင့် ဆူးလေဘုရားလမ်း",
        "lat": 16.779030,
        "lng": 96.158020,
        "tags": ["sakura tower", "office", "kyauktada", "ဆာကူရာတာဝါ", "ကျောက်တံတား"]
    },
    {
        "id": "off-08",
        "name": "Centrepoint Towers",
        "name_mm": "စင်တာပွိုင့်တာဝါ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Kyauktada",
        "township_mm": "ကျောက်တံတား",
        "road": "Sule Pagoda Road & Merchant Road",
        "road_mm": "ဆူးလေဘုရားလမ်း နှင့် ကုန်သည်လမ်း",
        "lat": 16.773520,
        "lng": 96.158830,
        "tags": ["centrepoint", "towers", "merchant rd", "kyauktada", "စင်တာပွိုင့်", "ကျောက်တံတား"]
    },
    {
        "id": "off-09",
        "name": "FMI Centre & The Campus",
        "name_mm": "အက်ဖ်အမ်အိုင် စင်တာ",
        "category": "Office Tower",
        "category_mm": "ရုံးတာဝါနှင့်စီးပွားရေးဗဟို",
        "township": "Pabedan",
        "township_mm": "ပန်းဘဲတန်း",
        "road": "Bogyoke Aung San Road",
        "road_mm": "ဗိုလ်ချုပ်အောင်ဆန်းလမ်း",
        "lat": 16.779530,
        "lng": 96.155020,
        "tags": ["fmi centre", "pabedan", "bogyoke road", "အက်ဖ်အမ်အိုင်", "ပန်းဘဲတန်း"]
    },
    {
        "id": "off-10",
        "name": "KBZ Bank Head Office (Diamond Inya Palace)",
        "name_mm": "ကမ္ဘောဇဘဏ် ဌာနချုပ် (KBZ Head Office)",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "U Wisara Road & Inya Road",
        "road_mm": "ဦးဝိစာရလမ်း အင်းယား",
        "lat": 16.843020,
        "lng": 96.138030,
        "tags": ["kbz bank", "head office", "mayangone", "bank", "ကမ္ဘောဇဘဏ်", "မရမ်းကုန်း"]
    },
    {
        "id": "off-11",
        "name": "CB Bank Head Office",
        "name_mm": "စီဘီဘဏ် ဌာနချုပ် (CB Bank Head Office)",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "Min Dhamma Road",
        "road_mm": "မင်းဓမ္မလမ်း",
        "lat": 16.871030,
        "lng": 96.131040,
        "tags": ["cb bank", "head office", "min dhamma", "mayangone", "စီဘီဘဏ်", "မရမ်းကုန်း"]
    },
    {
        "id": "off-12",
        "name": "AYA Bank Head Office (Rowe & Co)",
        "name_mm": "ဧရာဝတီဘဏ် ဌာနချုပ် (AYA Head Office)",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Kyauktada",
        "township_mm": "ကျောက်တံတား",
        "road": "Mahabandoola Road & Pansodan Road",
        "road_mm": "မဟာဗန္ဓုလလမ်း နှင့် ပန်းဆိုးတန်းလမ်း",
        "lat": 16.772040,
        "lng": 96.162030,
        "tags": ["aya bank", "head office", "kyauktada", "pansodan", "ဧရာဝတီဘဏ်", "ကျောက်တံတား"]
    },
    {
        "id": "off-13",
        "name": "Yoma Bank Head Office (Star City)",
        "name_mm": "ရိုးမဘဏ် ဌာနချုပ် (Yoma Bank Head Office)",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Thanlyin",
        "township_mm": "သန်လျင်",
        "road": "Star City Campus Road",
        "road_mm": "စတားစီးတီးနယ်မြေလမ်း",
        "lat": 16.756020,
        "lng": 96.243040,
        "tags": ["yoma bank", "star city", "thanlyin", "head office", "ရိုးမဘဏ်", "သန်လျင်"]
    },
    {
        "id": "off-14",
        "name": "MPT Telecom Headquarters",
        "name_mm": "မြန်မာ့ဆက်သွယ်ရေး MPT ဌာနချုပ်",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Botahtaung",
        "township_mm": "ဗိုလ်တထောင်",
        "road": "Bo Aung Kyaw Street",
        "road_mm": "ဗိုလ်အောင်ကျော်လမ်း",
        "lat": 16.774530,
        "lng": 96.167020,
        "tags": ["mpt", "telecom", "headquarters", "bo aung kyaw", "botahtaung", "မြန်မာ့ဆက်သွယ်ရေး"]
    },
    {
        "id": "off-15",
        "name": "ATOM Myanmar Telecom Headquarters",
        "name_mm": "ATOM ဆက်သွယ်ရေး ဌာနချုပ်",
        "category": "Corporate HQ",
        "category_mm": "ကော်ပိုရိတ်ဌာနချုပ်",
        "township": "Bahan",
        "township_mm": "ဗဟန်း",
        "road": "Myanmar Plaza Office Tower, Kabar Aye Pagoda Rd",
        "road_mm": "မြန်မာပလာဇာရုံးတာဝါ ကမ္ဘာအေးဘုရားလမ်း",
        "lat": 16.819540,
        "lng": 96.155520,
        "tags": ["atom", "telenor", "headquarters", "myanmar plaza", "bahan", "ဗဟန်း"]
    },

    # --- Industrial Zones (Yangon Major Ferry Destinations) ---
    {
        "id": "ind-01",
        "name": "Hlaing Tharyar Industrial Zone (Zone 1 & 2)",
        "name_mm": "လှိုင်သာယာ စက်မှုဇုန် (ဇုန် ၁ နှင့် ၂)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Bayint Naung Road & Kanaung Min Tha Gyi Rd",
        "road_mm": "ဘုရင့်နောင်လမ်း နှင့် ကနောင်မင်းသားကြီးလမ်း",
        "lat": 16.873040,
        "lng": 96.072030,
        "tags": ["hlaingtharyar", "industrial zone", "zone 1", "factory", "လှိုင်သာယာ", "စက်မှုဇုန်"]
    },
    {
        "id": "ind-02",
        "name": "Hlaing Tharyar Industrial Zone (Zone 3, 4 & 5)",
        "name_mm": "လှိုင်သာယာ စက်မှုဇုန် (ဇုန် ၃၊ ၄၊ ၅)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Anawrahta Industrial Road",
        "road_mm": "အနော်ရထာစက်မှုလမ်း",
        "lat": 16.898020,
        "lng": 96.051040,
        "tags": ["hlaingtharyar", "industrial zone", "zone 4", "zone 5", "factory", "လှိုင်သာယာ", "စက်မှုဇုန်"]
    },
    {
        "id": "ind-03",
        "name": "Shwe Pyi Thar Industrial Zone (Zone 1 & 2)",
        "name_mm": "ရွှေပြည်သာ စက်မှုဇုန် (ဇုန် ၁ နှင့် ၂)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "Shwepyitha",
        "township_mm": "ရွှေပြည်သာ",
        "road": "No. 4 Main Road",
        "road_mm": "အမှတ်(၄)လမ်းမကြီး",
        "lat": 16.955030,
        "lng": 96.108040,
        "tags": ["shwepyitha", "industrial zone", "zone 1", "factory", "ရွှေပြည်သာ", "စက်မှုဇုန်"]
    },
    {
        "id": "ind-04",
        "name": "South Dagon Industrial Zone (Zone 1 & 2)",
        "name_mm": "တောင်ဒဂုံ စက်မှုဇုန် (ဇုန် ၁ နှင့် ၂)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "South Dagon",
        "township_mm": "တောင်ဒဂုံ",
        "road": "Pyin Si Min Tha Gyi Road & No. 2 Main Road",
        "road_mm": "ပြင်စည်မင်းသားကြီးလမ်း နှင့် အမှတ်(၂)လမ်းမ",
        "lat": 16.852040,
        "lng": 96.223030,
        "tags": ["south dagon", "industrial zone", "factory", "တောင်ဒဂုံ", "စက်မှုဇုန်"]
    },
    {
        "id": "ind-05",
        "name": "East Dagon Industrial Zone",
        "name_mm": "အရှေ့ဒဂုံ စက်မှုဇုန်",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "East Dagon",
        "township_mm": "အရှေ့ဒဂုံ",
        "road": "Min Ye Kyaw Swar Road",
        "road_mm": "မင်းရဲကျော်စွာလမ်း",
        "lat": 16.875030,
        "lng": 96.252040,
        "tags": ["east dagon", "industrial zone", "factory", "အရှေ့ဒဂုံ", "စက်မှုဇုန်"]
    },
    {
        "id": "ind-06",
        "name": "Thilawa Special Economic Zone (SEZ Zone A & B)",
        "name_mm": "သီလဝါ အထူးစီးပွားရေးဇုန် (Thilawa SEZ)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "Kyauktan",
        "township_mm": "ကျောက်တန်း",
        "road": "Thanlyin-Kyauktan Highway",
        "road_mm": "သန်လျင်-ကျောက်တန်းလမ်းမကြီး",
        "lat": 16.662030,
        "lng": 96.278040,
        "tags": ["thilawa", "sez", "special economic zone", "kyauktan", "thanlyin", "သီလဝါ", "ကျောက်တန်း"]
    },
    {
        "id": "ind-07",
        "name": "Mingaladon Industrial Park (MIP)",
        "name_mm": "မင်္ဂလာဒုံ စက်မှုဥယျာဉ် (MIP)",
        "category": "Industrial Zone",
        "category_mm": "စက်မှုဇုန်",
        "township": "Mingaladon",
        "township_mm": "မင်္ဂလာဒုံ",
        "road": "No. 3 Main Road",
        "road_mm": "အမှတ်(၃)လမ်းမကြီး",
        "lat": 16.942030,
        "lng": 96.158020,
        "tags": ["mingaladon", "industrial park", "mip", "factory", "မင်္ဂလာဒုံ", "စက်မှုဇုန်"]
    },

    # --- Major Hospitals & Medical Hubs ---
    {
        "id": "hosp-01",
        "name": "Grand Hantha International Hospital",
        "name_mm": "ဂရင်းဟံသာ အပြည်ပြည်ဆိုင်ရာဆေးရုံ",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "Kamayut",
        "township_mm": "ကမာရွတ်",
        "road": "Lower Kyimyindaing Road & Nar Nat Taw Road",
        "road_mm": "အောက်ကြည့်မြင်တိုင်လမ်း နှင့် နာနတ်တောလမ်း",
        "lat": 16.812040,
        "lng": 96.121030,
        "tags": ["grand hantha", "hospital", "kamayut", "medical", "ဂရင်းဟံသာ", "ကမာရွတ်", "ဆေးရုံ"]
    },
    {
        "id": "hosp-02",
        "name": "Pun Hlaing Siloam Hospital",
        "name_mm": "ပန်းလှိုင် ဆေးရုံကြီး",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Pun Hlaing Golf Estate Road",
        "road_mm": "ပန်းလှိုင်ဂေါက်ကွင်းလမ်း",
        "lat": 16.853020,
        "lng": 96.079040,
        "tags": ["pun hlaing", "hospital", "siloam", "hlaingtharyar", "ပန်းလှိုင်", "လှိုင်သာယာ", "ဆေးရုံ"]
    },
    {
        "id": "hosp-03",
        "name": "Asia Royal Hospital",
        "name_mm": "အာရှတော်ဝင် ဆေးရုံ",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "Sanchaung",
        "township_mm": "စမ်းချောင်း",
        "road": "14 Baho Road",
        "road_mm": "ဗဟိုလမ်း အမှတ်(၁၄)",
        "lat": 16.801030,
        "lng": 96.132040,
        "tags": ["asia royal", "hospital", "baho road", "sanchaung", "အာရှတော်ဝင်", "စမ်းချောင်း", "ဆေးရုံ"]
    },
    {
        "id": "hosp-04",
        "name": "Victoria Hospital (9 Miles)",
        "name_mm": "ဗစ်တိုးရီးယား ဆေးရုံ",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "Mayangone",
        "township_mm": "မရမ်းကုန်း",
        "road": "68 Taw Win Road (9 Miles)",
        "road_mm": "သော်ဝင်လမ်း အမှတ်(၆၈) (၉မိုင်)",
        "lat": 16.867040,
        "lng": 96.136020,
        "tags": ["victoria", "hospital", "9 miles", "mayangone", "ဗစ်တိုးရီးယား", "မရမ်းကုန်း", "ဆေးရုံ"]
    },
    {
        "id": "hosp-05",
        "name": "Pinlon Hospital",
        "name_mm": "ပင်လုံ အထူးကုဆေးရုံ",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "North Dagon",
        "township_mm": "မြောက်ဒဂုံ",
        "road": "Pinlon Road (27 Ward)",
        "road_mm": "ပင်လုံလမ်း (၂၇ ရပ်ကွက်)",
        "lat": 16.869030,
        "lng": 96.205040,
        "tags": ["pinlon", "hospital", "north dagon", "medical", "ပင်လုံ", "မြောက်ဒဂုံ", "ဆေးရုံ"]
    },
    {
        "id": "hosp-06",
        "name": "Yangon General Hospital (YGH)",
        "name_mm": "ရန်ကုန်ပြည်သူ့ဆေးရုံကြီး (YGH)",
        "category": "Hospital",
        "category_mm": "ဆေးရုံ",
        "township": "Latha",
        "township_mm": "လသာ",
        "road": "Bogyoke Aung San Road",
        "road_mm": "ဗိုလ်ချုပ်အောင်ဆန်းလမ်း",
        "lat": 16.776040,
        "lng": 96.151030,
        "tags": ["ygh", "yangon general hospital", "bogyoke road", "latha", "ရန်ကုန်ပြည်သူ့ဆေးရုံကြီး", "လသာ"]
    },

    # --- Major Terminals & Transportation Hubs ---
    {
        "id": "term-01",
        "name": "Yangon International Airport (Terminal 1 & 2)",
        "name_mm": "ရန်ကုန်အပြည်ပြည်ဆိုင်ရာလေဆိပ်",
        "category": "Airport & Terminal",
        "category_mm": "လေဆိပ်နှင့်ကားဝင်း",
        "township": "Mingaladon",
        "township_mm": "မင်္ဂလာဒုံ",
        "road": "Airport Road / Pyay Road",
        "road_mm": "လေဆိပ်လမ်း / ပြည်လမ်း",
        "lat": 16.907030,
        "lng": 96.133040,
        "tags": ["airport", "terminal 1", "terminal 2", "mingaladon", "yia", "ရန်ကုန်လေဆိပ်", "မင်္ဂလာဒုံ"]
    },
    {
        "id": "term-02",
        "name": "Aung Mingalar Highway Bus Terminal",
        "name_mm": "အောင်မင်္ဂလာ အဝေးပြေးကားဝင်းကြီး",
        "category": "Airport & Terminal",
        "category_mm": "လေဆိပ်နှင့်ကားဝင်း",
        "township": "Mingaladon",
        "township_mm": "မင်္ဂလာဒုံ",
        "road": "Pyidaungsu Main Road",
        "road_mm": "ပြည်ထောင်စုလမ်းမကြီး",
        "lat": 16.928040,
        "lng": 96.168030,
        "tags": ["aung mingalar", "highway bus terminal", "mingaladon", "အောင်မင်္ဂလာ", "အဝေးပြေး", "မင်္ဂလာဒုံ"]
    },
    {
        "id": "term-03",
        "name": "Dagon Ayeyar Highway Bus Terminal",
        "name_mm": "ဒဂုံဧရာ အဝေးပြေးကားဝင်း",
        "category": "Airport & Terminal",
        "category_mm": "လေဆိပ်နှင့်ကားဝင်း",
        "township": "Hlaingtharyar",
        "township_mm": "လှိုင်သာယာ",
        "road": "Yangon-Pathein Highway",
        "road_mm": "ရန်ကုန်-ပုသိမ်လမ်းမကြီး",
        "lat": 16.851020,
        "lng": 96.042040,
        "tags": ["dagon ayeyar", "highway bus terminal", "hlaingtharyar", "ဒဂုံဧရာ", "အဝေးပြေး", "လှိုင်သာယာ"]
    },
    {
        "id": "term-04",
        "name": "Yangon Central Railway Station",
        "name_mm": "ရန်ကုန်ဘူတာကြီး",
        "category": "Airport & Terminal",
        "category_mm": "လေဆိပ်နှင့်ကားဝင်း",
        "township": "Mingalar Taung Nyunt",
        "township_mm": "မင်္ဂလာတောင်ညွန့်",
        "road": "Kunchan Road",
        "road_mm": "ကွမ်းခြံလမ်း",
        "lat": 16.782040,
        "lng": 96.161030,
        "tags": ["yangon central railway station", "train station", "mingalar taung nyunt", "ရန်ကုန်ဘူတာကြီး"]
    }
]

with open('public/yangon_offices_db.json', 'w', encoding='utf-8') as f:
    json.dump({
        "version": "1.0",
        "description": "Yangon Major Offices, City Mart Supermarket Branches, Towers, Industrial Zones, and Commercial POIs",
        "total_count": len(offices_and_pois),
        "places": offices_and_pois
    }, f, ensure_ascii=False, indent=2)

print(f"Generated {len(offices_and_pois)} Yangon Offices and POIs into public/yangon_offices_db.json")
